### ISSUE TITLE
Hey !

### ISSUE THREAD

**Issue by officialyashx** [DEVSHAH-24/Backdrop_#1]
Hello Dev,
This seems like a promising project ! Is this source open for me to use ? 
Also, do you have a tutorial video or something that can help ? I'm a beginner at this and need to build a app. 
Please help.

Or maybe if you have telegram then can we talk ? @dedasfuck this is my username.

Thank you so much.

**Comment by DEVSHAH-24** [comment]
Hello Yash,
This project ain't open source. 
For a complete starter, Angela Yu's course is a nice way to go. Udacity's free course is good too.
YT has some nice channels like MTECHVIRAL , Smartherd , etc.
